name: baby-tritium-transport-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - numpy
  - pyvista
  - openmc
  - python-gmsh
  - matplotlib
  - festim=2.0a0
  - pip
  - pip:
    - git+https://github.com/LIBRA-project/libra-toolbox@v0.5
    - openmc-data-downloader
    - git+https://github.com/festim-dev/openmc2dolfinx
    - git+https://github.com/festim-dev/foam2dolfinx