name: baby-tritium-transport-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - numpy
  - ipykernel
  - pyvista
  - openmc
  - python-gmsh
  - matplotlib
  - festim=2.0a2
  - pip
  - pip:
    - libra-toolbox>=0.5
    - openmc-data-downloader
    - git+https://github.com/festim-dev/openmc2dolfinx
    - git+https://github.com/festim-dev/foam2dolfinx
    - morethemes